### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by emarde** [passaH2O/GeoNet#2]
- The newest version of python does not accept print as an open command. Now, it is a function that requires parentheses- e.g., print(). Is it possible to update the code to reflect this?

- Can these be written into a package that can be implemented in iPython Notebooks?

**Comment by bkgelder** [comment]
Is there a newer version that supports the currently available versions of GRASS and references currently available versions of MapServer and GDAL? If not, are you able to provide links to the versions given in the tutorial?

**Comment by paolaPassaH2O** [comment]
We are currently updating GeoNet and a new version will be posted soon. Also, note that most of GeoNet is integrated into GeoFlood and tutorials are available for it.
